### PR TITLE
first submission

### PR DESCRIPTION
**Pull request by youforlia**

### CODE REVIEW

**Review by gennady-bars — COMMENTED** [review]
Dear Steve , (**Please, expand the general comment ↓**)

Unfortunately I have to reject the project:



* In **Files changed** there must be the code that should be reviewed. So, all changes from the last sprint should be there. But now you have only 1 file there. I'm not able to leave comments in your code. Please, try to send me a new pull request with all files changed. One of the options is to make a new **branch** from `main` then delete all code from `main`, commit it, push it and after that you need to make a pull request (so, there will be the whole code of the project)

**Comment by youforlia** [comment]
Hello Gennady,

Steve is my employer, please call me Sarla :) by the way I have resubmiited the PR link, I have not deleted the code from my main because I'm scared to do it and so I tried a different method. I'm not sure if it works, but I hope it did. Let me know. Thanks!

**Review by gennady-bars — COMMENTED** [review]
Dear Sarla,


* Please, check this link in discord how to resolve the pull request https://discordapp.com/channels/1078663743568883783/1164579889303797800 
* In **Files changed** there must be the code that should be reviewed. So, all changes from the last sprint should be there. But now you have only 1 file there. I'm not able to leave comments in your code. Please, try to send me a new pull request with all files changed. One of the options is to make a new **branch** from `main` then delete all code from `main`, commit it, push it and after that you need to make a pull request (so, there will be the whole code of the project). Or  please, check this link in discord how to resolve the pull request https://discordapp.com/channels/1078663743568883783/1164579889303797800

**Review by gennady-bars — COMMENTED** [review]
Dear Sarla,


* Please, check this link in discord how to resolve the pull request https://discordapp.com/channels/1078663743568883783/1164579889303797800 
* In **Files changed** there must be the code that should be reviewed. So, all changes from the last sprint should be there. But now you have only 3 files there. I'm not able to leave comments in your code. Please, try to send me a new pull request with all files changed. One of the options is to make a new **branch** from `main` then delete all code from `main`, commit it, push it and after that you need to make a pull request (so, there will be the whole code of the project). Or  please, check this link in discord how to resolve the pull request https://discordapp.com/channels/1078663743568883783/1164579889303797800

**Pull request closed without merging**
